### ISSUE TITLE
GPS Tutorial: fprime-gds won't launch - dumb user error?

### ISSUE THREAD

**Issue by timmyd7777** [nasa/fprime#1118]
I'm able to build the GPS tutorial using the older repository ("gps-application" branch) here:
https://github.com/LeStarch/fprime/tree/gps-application

However, the instructions to actually run the demo fail for me.  The first step is to launch fprime-gds as follows:

`fprime-gds -d . -n`

This gives me a usage statement, and this error: `fprime-gds: error: unrecognized arguments: -d .`

The GpsApp itself does actually start, and I see console log output indicating that it successfully opened /dev/ttyACM0, but only if I launch it as superuser, i.e.

`sudo bin/Linux/GpsApp -a 127.0.0.1 -p 50000 -d /dev/ttyACM0`

I am building and running everything on a linux host computer - I'm not yet trying to run GpsApp on a separate computer from the machine running fprime-gds.

I understand that this GpsApp tutorial is several years out of date with the most current F-Prime distribution - but I am building and running everything from LeStarch's older repository (as mentioned above).  So I'd think this should work.

Is there a dumb newbie mistake that I'm making?

**Comment by LeStarch** [comment]
First off, I'd recommend looking at: https://github.com/fprime-community/gps-tutorial as this is where the new version of the code has moved.  That old branch hasn't been maintained in a long time.

To answer your specific questions: `sudo` is likely required because you don't have permissions to read `/dev/ttyACM0` on your user.....try adding your user to the `dialout` group.  This usually fixes the issue.

Next, what version of fprime-gds did you install?  fprime-gds has evolved a bit and thus those old instructions are probably out of date.  If you have the newest fprime-gds:

```
fprime-gds --dictionary </path/to/dictionary> -n
```

and the run the binary.

Since this is more of a discussion than an issue, I am going to convert this over to the Discussions.
