### ISSUE TITLE
[Warning]Failed to find settings file <path>/fprime/Ref/settings.ini

### ISSUE THREAD

**Issue by KapitanJon** [nasa/fprime#1207]
This is my first time working with F'. During the installation process I followed the instructions as listed in the INSTALL.md. The install went well without any warning or errors. However when I reached the "Testing F' Autocoder via building Ref application" I got the following error when running the `fprime-util generate`

`[WARNING] Failed to find settings file: /home/jons/fprime/Ref/settings.ini`

I apologize if this is a very novice issue, but I have been mulling over this for some time now trying to figure it out.

Ubuntu:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

Cmake Version:
3.16.3

OpenJDK:
"11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

Python:
3.8.10

**Comment by ThibFrgsGmz** [comment]
If I remember correctly this warning just notifies the user that F Prime will take its default values for the build (source location, compiler etc)

The settings.ini file is a way for the user to customize F Prime in case of an exotic compiler or if he encapsulates F Prime as a sub module of his project for example.

Look at the complete settings.ini guide for more information 
https://github.com/nasa/fprime/blob/devel/docs/UsersGuide/user/settings.md

Related previous issue https://github.com/nasa/fprime/issues/230

**Comment by LeStarch** [comment]
@ThibFrgsGmz you are correct, this just means that Ref uses "default" settings as no `settings.ini` was specified.

I am going to close this issue.  Feel free to open it again if there are more issues.

**Comment by LeStarch** [comment]
As a side note, perhaps that message should be less ominous.  E.g.

```
[INFO] Using default deployment settings. Did not find settings file: /home/jons/fprime/Ref/settings.ini
```

**Comment by ThibFrgsGmz** [comment]
@LeStarch I agree that it is somewhat ominous. Personally I still classify it as a warning.

I'm more in favor of adding a ``settings.ini`` directly to ``Ref``. This has the advantage of highlighting this file directly in the repo to the user.

But your proposal does not shock me more than that, it makes sense and the turn of phrase is suitable.

**Comment by LeStarch** [comment]
@ThibFrgsGmz here is the tradeoff that has caused us not to add one to Ref: `settings.ini` is not strictly required, but `Ref` is the only example where it would be correct to not provide it.

`settings.ini` enables deployments to use F´ as a subdirectory or separate library.  Project may (but should not) place their deployments directly in a clone-and-owned fprime checkout.  Here, no `settings.ini` is needed.  `Ref` is the only example the framework would ever provide that is within the `fprime` framework (Note: RPI uses a setting.ini for toolchain information).

Since new projects should never follow this model and thus Ref **should be** the only need for a "not required settings.ini", perhaps we should just add one to ref and call it "required".  This warning would go away, a better model would be demonstrated, and the feature would be supported but not demonstrated.
