### ISSUE TITLE
strnlen is not standard C++11 and not implemented in fprime

### ISSUE THREAD

**Issue by kevin-f-ortega** [nasa/fprime#1342]
| | |
|:---|:---|
|**_F´ Version_**| 47afb72e1f2cb79c1ab475458b0ed3faca5d317c|
|**_Affected Component_**|  Any function using strnlen |
---
## Problem Description

strnlen is not part of the C++11 standard.
When compiling with C++11 (without any extensions e.g. gnu++11), the compiler complains that strnlen is not defined.

## How to Reproduce

1.  Use only -std=c++11 without any extensions when compiling
2.
3.

## Expected Behavior

strnlen should be defined.

Note: @bocchino would like to review.

**Comment by LeStarch** [comment]
**Note:** we need to implement our own `strnlen` implementation and put it in `StringUtils::string_length()`.  I'd recommend not even creating the `strnlen` function and just putting an implementation directly in `string_length`.

If users want to call `strnlen` from their code, and implementation is up to them. Otherwise, use `StringUtils::string_length()`.

@kevin-f-ortega does this make sense?

**Comment by kevin-f-ortega** [comment]
@LeStarch that make sense. Thanks!
