### ISSUE TITLE
Cross Compile for MacOS on Raspberry Pi

### ISSUE THREAD

**Issue by aaronbuchwald** [nasa/fprime#138]
I'm currently trying to cross-compile for raspberry pi on MacOS as I'm trying to do the raspberry pi tutorial here: https://github.com/nasa/fprime/tree/master/RPI. I'm trying to utilize the compiler here, but getting the error that my computer cannot execute the binary file: https://github.com/raspberrypi/tools/blob/master/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc

I know it says that FPrime is now compatible with MacOS, so were you guys able to find a workaround, am I likely just doing this incorrectly, or is it still not possible to cross-compile for rpi on macos?

Also, I already checked to make sure that the issue wasn't the way that I had updated the location within the raspberrypi cmake toolchain file here: https://github.com/nasa/fprime/blob/master/cmake/toolchain/raspberrypi.cmake and the binary file is in the correct place, and when I go to the location and try to run it by itself I get the same error that it can't execute the binary file.

**Comment by LeStarch** [comment]
The issue is the tools supplied from the  Raspberry PI group is pre-compiled for Linux.  I don't know of any tools provided to cross compile for RPI that execute on Mac OSX.  If you find some tools from them that run on OS X, it would be fairly straight forward to integrate them with F prime,

We usually use a VM to cross compile for the RPI to get around this.
