### ISSUE TITLE
GenericHub inconsistent type for size

### ISSUE THREAD

**Issue by gjwatney** [nasa/fprime#2173]
| | |
|:---|:---|
|**_F´ Version**|v3.2.0 |
|**_Affected Component_**|Svc/GenericHub   |
---
## Problem Description

Svc/GenericHub sendData() serializes the size of the buffer as U32, but in dataIn_handler() the size is deserialized as FwBuffSizeType which is a U16.

## How to Reproduce

1.  Connect the GenericHub to a component that pushes in a large data buffer to the buffersIn port (ie 80 000 bytes)
2.  The GenericHub should assert on line 92:  FW_ASSERT(rawSize == static_cast<U32>(size));

## Expected Behavior

A description of the expected behavior.

**Comment by LeStarch** [comment]
The issue stems from the fact that GenericBuffer uses FwBuffSizeType to hold size in the serialized message.  This is configurable, but defaults to `U16`.  

Although GenericHub should probably assert on overflow rather than silently overflow, the real issue is that without changing configuration, a message overflows at 65535 bytes due to the serialization code it uses.  Thus GH cannot send buffers larger than that
