### ISSUE TITLE
Add A Verify F´  Tools Version at Install

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#2234]
Users following tutorials get confused when the prompts do not match the tool output.  We should add a step to verify tool versions.

In the write-up for the tutorial, add a step to run:

```
fprime-util --help
```

And verify the version matches the expected version of the tutorial write-up.  If not, add a note saying some prompts may differ.

**Comment by benjiforster** [comment]
Could I work on this?

**Comment by thomas-bc** [comment]
@benfrstr feel free to make any contributions to the tutorial repositories you think would make user experience / understanding better! 
For this specific issue, I think it might not be necessary anymore, since we reference the install guide and have a better process to keep tutorials in sync than we had at the time this ticket was created.

**Comment by benjiforster** [comment]
@thomas-bc I don't want to contribute anything unnecessary, so it's up to you. I will look for another good first issue if this issue is no longer applicable.

**Comment by thomas-bc** [comment]
Closing as the tutorials have been modified to reference the install guide.
