### ISSUE TITLE
Os unit tests fail with parallel build

### ISSUE THREAD

**Issue by bocchino** [nasa/fprime#2552]
| | |
|:---|:---|
|**_F´ Version_**| Head of `devel`, commit 58c21418aac3162156299ad6e0153a1e94288b45|
|**_Affected Component_**| `Os`  |
|**_Platform_**| Mac OS X, Intel Mac |
---
## Problem Description

When running `fprime-util check --jobs 4`, one of the tests reports it can't find a file and fails.

## Example Output

```
test 4
    Start 4: StubFileTest
Could not find executable /Users/bocchino/JPL/Tools/FPrime/bocchino/fprime/build-fprime-automatic-native-ut/bin/Darwin/StubFileTest
```

## How to Reproduce

1. Run `fprime-util check --jobs 4` in the `Os` directory.

**Comment by LeStarch** [comment]
Note: the parallel flag is superfluous.  This occurs with the `fprime-util check --jobs 1` single thread execution too.

This occurs because the `Os_check` target (for running all Os UTs) is not properly being listed as having dependencies on two test executables: `PosixFile` and `StubFile`.  Thus those tests run, but the executables are not built.
