### ISSUE TITLE
The only command boolean argument value GDS interprets as false is False (not 0, false, etc)

### ISSUE THREAD

**Issue by nabcouwer** [nasa/fprime#343]
| | |
|:---|:---|
|**devel as of 2021-01**| |
|**GDS**|   |
---
## Problem Description

https://groups.google.com/g/fprime-community/c/wdzHHbBXKfU

When I make an F' command with a bool arg, the only value that GDS seems to interpret as false is:

False

(no quotes, capitalized)

0, false, "false", 'false' all get interpreted as true. 

![Screenshot from 2021-01-27 12-55-20](https://user-images.githubusercontent.com/2354310/106071183-bd3ce400-60ba-11eb-959c-e7da6daec360.png)

## How to Reproduce

1. Create a command with an arg of type "bool", add it to a deployment.
2. Try sending the command to the deployment with many of the values one might reasonably assume GDS might interpret as false (0, false, "false", 'false')
3. Look at the GDS command history and see that the arguments got interpreted as true.

## Expected Behavior

GDS would ideally give a true/false dropdown for bool arguments, or interpret entries of 0, false, etc as false.

Thanks!

**Comment by saba-ja** [comment]
The issue is the following:
https://github.com/nasa/fprime/blob/5d631af802664719a2de61bf22cf0a1cf3b2dc9f/Gds/src/fprime_gds/common/data_types/cmd_data.py#L161-L166

To fix, the following can be used in Gds/src/fprime_gds/common/data_types/cmd_data.py:
```
def convert_arg_value(self, arg_val, arg_type):
       ...
        if isinstance(arg_type, BoolType):
            if isinstance(arg_val, bool):
                av = bool(value)
            else:
                value = str(arg_val).lower().replace('"','').replace("'",'').strip()
                if value in ("true", "t", "1", "yes", "y"):
                    av = True
                elif value in ("false", "f", "0", "no", "n"):
                    av = False
                else:
                    raise CommandArgumentException(
                        "Argument value is not a valid boolean"
                    )
            arg_type.val = av
       ...
```
It will support ("true", "t", "1", "yes", "y") for True and ("false", "f", "0", "no", "n") for False. Single or double quotes, trailing spaces, letter case(Lower, Uppercase) will be ignored. Anything else will raise CommandArgumentException

Demo cases:
0 is false
![image](https://user-images.githubusercontent.com/35859004/108590380-198ccf80-7318-11eb-8153-6eb3873ba800.png)
f is false
![image](https://user-images.githubusercontent.com/35859004/108590386-227da100-7318-11eb-962f-b19e958fb49c.png)
1 is true
![image](https://user-images.githubusercontent.com/35859004/108590389-26112800-7318-11eb-822d-a76a44f5c44f.png)
