### ISSUE TITLE
fprime-util impl autocoder does not use return type

### ISSUE THREAD

**Issue by metzdigital** [nasa/fprime#419]
The return type used in the interface definition is ignored when using `fprime-util impl`, the autocoder return type is hard coded to always be `void`

![image](https://user-images.githubusercontent.com/2592986/109230394-a6e97d00-7779-11eb-9b3a-55a77334fc37.png)

After manually replacing `void` with `Backplane::CardConfigReturn` I could get this to compile. 

Here is my interface definition:
```
<interface name="CardConfig" namespace="Backplane">
    <comment>
        Port to grab card configuration details used by the backplane manager at initialization
    </comment>
    <import_serializable_type>Backplane/Common/CardConfigReturnSerializableAi.xml</import_serializable_type>
    <args>
        <!-- No args only the return is important -->
    </args>
    <return type="Backplane::CardConfigReturn" pass_by="value"> </return>
</interface>
```

**Comment by saba-ja** [comment]
## Root cause:

The problem is from line 61

https://github.com/nasa/fprime/blob/598f850b0784735acc9a8b6e367a9cd5acdd0972/Autocoders/Python/src/fprime_ac/generators/templates/impl/hpp.tmpl#L53-L64

and 

https://github.com/nasa/fprime/blob/598f850b0784735acc9a8b6e367a9cd5acdd0972/Autocoders/Python/src/fprime_ac/generators/templates/impl/cpp.tmpl#L55-L70

The template always adds `void` for user-defined input port types.

## Fix:

To resolve the issue the following can be done:

In fprime/Autocoders/Python/src/fprime_ac/generators/templates/impl/hpp.tmpl
```c++
  #for $instance, $type, $sync, $priority, $full, $role, $max_num in $typed_user_input_ports:
      //! Handler implementation for $instance
      //!
      #set $return_type = $port_return_type_strs[$instance]
      ${return_type}${instance}_handler(
$emit_port_params([ $param_portNum ] + $port_params[$instance])
      );
```

In fprime/Autocoders/Python/src/fprime_ac/generators/templates/impl/cpp.tmp
```c++
  #for $instance, $type, $sync, $priority, $full, $role, $max_num in $typed_user_input_ports:
  #set $return_type = $port_return_type_strs[$instance]
  ${return_type}${name}ComponentImpl ::
    ${instance}_handler(
$emit_port_params([ $param_portNum ] + $port_params[instance])
    )
  {
  #if $return_type[:4] == "void":    
    // TODO
  #else:
    // TODO return
  #end if
  }
```

## Output after fix:

hpp before:
![image](https://user-images.githubusercontent.com/35859004/109255620-3a867200-77a9-11eb-8cba-cf2669afe5de.png)

hpp after:
![image](https://user-images.githubusercontent.com/35859004/109255681-59850400-77a9-11eb-8fd6-dcbe71c0ae67.png)

cpp before:
![image](https://user-images.githubusercontent.com/35859004/109255751-791c2c80-77a9-11eb-9fb6-e9f47ad2a5ce.png)

cpp after:
![image](https://user-images.githubusercontent.com/35859004/109255792-89cca280-77a9-11eb-91db-6fcb0825b30b.png)


## Bonus fix:

`user-defined serial input ports` is also always `void`:

https://github.com/nasa/fprime/blob/598f850b0784735acc9a8b6e367a9cd5acdd0972/Autocoders/Python/src/fprime_ac/generators/templates/impl/hpp.tmpl#L69-L81

https://github.com/nasa/fprime/blob/598f850b0784735acc9a8b6e367a9cd5acdd0972/Autocoders/Python/src/fprime_ac/generators/templates/impl/cpp.tmpl#L72-L84

The same approach can be used to fix the above as well.

**Comment by LeStarch** [comment]
@saba-ja you should post a PR to fix the return type!    Serial ports shouldn't return anything...i don't think...so likely we only need the first fix.
