### ISSUE TITLE
File Downlink File Names

### ISSUE THREAD

**Issue by LeStarch** [nasa/fprime#516]
| | |
|:---|:---|
|**_F´ Version_**| 1.5.3 |
|**_Affected Component_**| FileDownlink  |
---
## Problem Description

Some file names reportedly break FileDownlink. 

## How to Reproduce

"e.g. a source file name of "/tmp/Screen_Shot_2020-03-26_at_9.19.28_PM.png" breaks it with format error."

**Comment by Joshua-Anderson** [comment]
The default F' FW_CMD_STRING_MAX_SIZE is 40 characters. `/tmp/Screen_Shot_2020-03-26_at_9.19.28_PM.png` is 45 characters, longer the max supported string length.

I'm tempted to close this as expected behavior, but we should start a conversation about how to handle strings in F' better. For example, the command definition for FileDownlink.SendFile defines source file as a string of length 100. Should requesting a command string size longer than FW_CMD_STRING_MAX_SIZE somehow result in a warning?

**Comment by timcanham** [comment]
We should make this part of a larger effort to define constants in a way that the autocoder, ground system, and software can all use them and that way we can add autocoder rules to detect issues like this.

**Comment by LeStarch** [comment]
@timcanham and @Joshua-Anderson, I agree with both here.  Closing in favor of: https://github.com/nasa/fprime/issues/530
